name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Update conda
      run: |
        conda update -n base -c defaults conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict

    - name: Install mamba
      run: |
        conda install mamba -n base -c conda-forge

    - name: Install dependencies using mamba
      run: |
        mamba install flake8 -c conda-forge
        mamba install numpy -c conda-forge

    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
